import { IBM_Plex_Sans_Arabic, Readex_Pro, Rubik } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import {
  ClerkProvider,
 
} from '@clerk/nextjs'
import Provider from "./Provider";

const rubik = Rubik({
  subsets: ["arabic", "latin"],      // يدعم نص عربي + أرقام/إنكليزي
  weight: ["300","400","500","700","800","900"], // اختَر ما تحتاجه
  variable: "--font-rubik",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="ar" dir="rtl" className={`${rubik.variable} antialiased`}>
      
      <body className="font-sans antialiased">
     
       
        <Provider>
          
        {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
